export const ADD_PRODUCT_DETAILS = 'ADD_PRODUCT_DETAILS';
export const FETCH_ADDED_PRODUCT_DETAILS = 'FETCH_ADDED_PRODUCT_DETAILS';
export const SAVE_INVOICE_DETAILS_TO_PREVIEW = 'SAVE_INVOICE_DETAILS_TO_PREVIEW';
